import 'dart:async';
import 'dart:convert';
import 'package:http/http.dart' as http;
import '../config/app_config.dart';
import '../models/ad_campaign.dart';
import '../models/channel.dart';
import '../models/contest.dart';
class RadioApiClient {
 RadioApiClient({http.Client? client}):_client=client??http.Client();final http.Client _client;
 Future<http.Response> _getWithRetry(Uri uri,{Duration timeout=const Duration(seconds:10),int attempts=2})async{Object? lastError;for(var attempt=1;attempt<=attempts;attempt++){try{return await _client.get(uri,headers:const{'Accept':'application/json'}).timeout(timeout);}on http.ClientException catch(e){lastError=e;}on TimeoutException catch(e){lastError=e;}if(attempt<attempts)await Future<void>.delayed(const Duration(milliseconds:350));}throw lastError??const RadioApiException('No fue posible conectar con la API.');}
 Future<List<Channel>> fetchSomosRadioChannels()async{if(AppConfig.radioApiBaseUrl.isEmpty)return _demoChannels;final response=await _getWithRetry(Uri.parse('${AppConfig.radioApiBaseUrl}/stations/${AppConfig.stationSlug}'));if(response.statusCode==404&&AppConfig.isConceptDemo)return _demoChannels;if(response.statusCode<200||response.statusCode>=300)throw RadioApiException('La API respondió ${response.statusCode}.');final items=_extractChannels(jsonDecode(response.body));return items.whereType<Map>().map((x)=>Channel.fromJson(x.cast<String,dynamic>())).where((x)=>x.isActive).toList();}
 Future<List<AdCampaign>> fetchAds({required String placement})async{if(AppConfig.radioApiBaseUrl.isEmpty)return const[];final uri=Uri.parse('${AppConfig.radioApiBaseUrl}/ads').replace(queryParameters:{'station_slug':AppConfig.stationSlug,'placement':placement});final response=await _getWithRetry(uri,timeout:const Duration(seconds:3));if(response.statusCode<200||response.statusCode>=300)throw RadioApiException('No fue posible consultar la publicidad (${response.statusCode}).');final decoded=jsonDecode(response.body);if(decoded is! Map<String,dynamic>||decoded['data'] is! List)throw const RadioApiException('Formato inesperado en la respuesta de publicidad.');return(decoded['data']as List).whereType<Map>().map((x)=>AdCampaign.fromJson(x.cast<String,dynamic>())).where((x)=>x.imageUrl.isNotEmpty).toList();}
 Future<void> recordAdImpression(int id)=>_recordAdEvent(id,'impression');Future<void> recordAdClick(int id)=>_recordAdEvent(id,'click');Future<void> _recordAdEvent(int id,String event)async{if(AppConfig.radioApiBaseUrl.isEmpty)return;try{await _client.post(Uri.parse('${AppConfig.radioApiBaseUrl}/ads/$id/$event'),headers:const{'Accept':'application/json'}).timeout(const Duration(seconds:3));}catch(_){}}
 Future<SongRequestResult> submitSongRequest({required String channelSlug,required String listenerName,required String song,required String artist,String? dedication})async{if(AppConfig.radioApiBaseUrl.isEmpty)throw const RadioApiException('La API no está configurada.');final response=await _client.post(Uri.parse('${AppConfig.radioApiBaseUrl}/song-requests'),headers:const{'Accept':'application/json','Content-Type':'application/json'},body:jsonEncode({'station_slug':AppConfig.stationSlug,'channel_slug':channelSlug,'listener_name':listenerName.trim(),'song':song.trim(),'artist':artist.trim(),'dedication':dedication?.trim()})).timeout(const Duration(seconds:12));dynamic decoded;try{decoded=jsonDecode(response.body);}catch(_){decoded=null;}if(response.statusCode<200||response.statusCode>=300){var message='No fue posible enviar la solicitud.';if(decoded is Map<String,dynamic>){final m=decoded['message']?.toString().trim();if(m!=null&&m.isNotEmpty)message=m;}throw RadioApiException(message);}if(decoded is! Map<String,dynamic>||decoded['data']is! Map)throw const RadioApiException('Formato inesperado en la respuesta de la API.');final m=(decoded['data']as Map).cast<String,dynamic>();return SongRequestResult(id:m['id']as int?,status:m['status']?.toString()??'new',station:m['station']?.toString()??'Somos Radio',channel:m['channel']?.toString()??'',message:decoded['message']?.toString()??'Solicitud recibida correctamente.');}
 Future<void> registerPushDevice({required String token,String platform='android',String? appVersion,String? deviceName})async{if(AppConfig.radioApiBaseUrl.isEmpty)throw const RadioApiException('La API no está configurada.');final response=await _client.post(Uri.parse('${AppConfig.radioApiBaseUrl}/push-devices'),headers:const{'Accept':'application/json','Content-Type':'application/json'},body:jsonEncode({'token':token,'platform':platform,if(appVersion!=null)'app_version':appVersion,if(deviceName!=null)'device_name':deviceName})).timeout(const Duration(seconds:12));if(response.statusCode<200||response.statusCode>=300)throw RadioApiException('No fue posible registrar el dispositivo (${response.statusCode}).');}
 Future<Contest?> fetchActiveContest()async{if(AppConfig.radioApiBaseUrl.isEmpty)return null;final uri=Uri.parse('${AppConfig.radioApiBaseUrl}/contests/active').replace(queryParameters:{'station_slug':AppConfig.stationSlug});final response=await _getWithRetry(uri);if(response.statusCode<200||response.statusCode>=300)throw RadioApiException('No fue posible consultar la dinámica.');final decoded=jsonDecode(response.body);final data=decoded is Map?decoded['data']:null;if(data==null)return null;if(data is! Map)throw const RadioApiException('Formato inesperado de la dinámica.');return Contest.fromJson(data.cast<String,dynamic>());}
 Future<ContestEntryResult?> fetchPendingContestPrize(String deviceKey)async{if(AppConfig.radioApiBaseUrl.isEmpty)return null;final uri=Uri.parse('${AppConfig.radioApiBaseUrl}/contests/pending-prize').replace(queryParameters:{'device_key':deviceKey});final response=await _getWithRetry(uri);if(response.statusCode<200||response.statusCode>=300)throw RadioApiException('No fue posible consultar tu premio.');final decoded=jsonDecode(response.body);final data=decoded is Map?decoded['data']:null;if(data==null)return null;if(data is! Map)throw const RadioApiException('Formato inesperado del premio.');return ContestEntryResult.fromJson(data.cast<String,dynamic>());}
 Future<ContestEntryResult> submitContestEntry({required int contestId,required String deviceKey,required String selectedOption,String? listenerName,String? phone})async{final response=await _client.post(Uri.parse('${AppConfig.radioApiBaseUrl}/contests/$contestId/entries'),headers:const{'Accept':'application/json','Content-Type':'application/json'},body:jsonEncode({'device_key':deviceKey,'selected_option':selectedOption,'listener_name':listenerName?.trim(),'phone':phone?.trim()})).timeout(const Duration(seconds:12));dynamic decoded;try{decoded=jsonDecode(response.body);}catch(_){decoded=null;}if(response.statusCode<200||response.statusCode>=300)throw RadioApiException(decoded is Map&&decoded['message']!=null?decoded['message'].toString():'No fue posible registrar tu participación.');final data=decoded is Map?decoded['data']:null;if(data is! Map)throw const RadioApiException('Formato inesperado de participación.');return ContestEntryResult.fromJson(data.cast<String,dynamic>());}
 List<dynamic> _extractChannels(dynamic d){if(d is Map<String,dynamic>){if(d['channels']is List)return d['channels'];if(d['data']is Map<String,dynamic>&&d['data']['channels']is List)return d['data']['channels'];}throw const RadioApiException('Formato inesperado en la respuesta de la API.');}
 static const _demoChannels=<Channel>[Channel(id:null,name:'89.1 FM',slug:'89-1-tuxtla',streamUrl:'',isActive:true,metadata:{'frequency':'89.1 FM','city':'Tuxtla Gutiérrez','source':'demo'}),Channel(id:null,name:'102.9 FM',slug:'102-9-san-cristobal',streamUrl:'',isActive:true,metadata:{'frequency':'102.9 FM','city':'San Cristóbal de las Casas','source':'demo'})];
}
class SongRequestResult{const SongRequestResult({required this.id,required this.status,required this.station,required this.channel,required this.message});final int? id;final String status,station,channel,message;}
class RadioApiException implements Exception{const RadioApiException(this.message);final String message;@override String toString()=>message;}
