import 'dart:math';
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../../core/api/radio_api_client.dart';
import '../../core/models/contest.dart';
import '../../core/theme/app_theme.dart';
class ContestPage extends StatefulWidget{const ContestPage({super.key});@override State<ContestPage> createState()=>_ContestPageState();}
class _ContestPageState extends State<ContestPage>{
 final _api=RadioApiClient();final _name=TextEditingController();final _phone=TextEditingController();Contest? _contest;ContestEntryResult? _result;String? _selected;String? _error;bool _loading=true,_sending=false;
 @override void initState(){super.initState();_load();}@override void dispose(){_name.dispose();_phone.dispose();super.dispose();}
 Future<String> _deviceKey()async{final prefs=await SharedPreferences.getInstance();var key=prefs.getString('contest_device_key');if(key==null){final r=Random.secure();key='${DateTime.now().microsecondsSinceEpoch}-${List.generate(4,(_)=>r.nextInt(1<<32).toRadixString(16)).join()}';await prefs.setString('contest_device_key',key);}return key;}
 Future<void> _load()async{try{final key=await _deviceKey();final pending=await _api.fetchPendingContestPrize(key);if(pending!=null){if(mounted)setState((){_result=pending;_loading=false;});return;}final c=await _api.fetchActiveContest();if(mounted)setState((){_contest=c;_loading=false;});}catch(e){if(mounted)setState((){_error=e.toString();_loading=false;});}}
 Future<void> _submit()async{if(_contest==null||_selected==null||_sending)return;setState(()=>_sending=true);try{final result=await _api.submitContestEntry(contestId:_contest!.id,deviceKey:await _deviceKey(),selectedOption:_selected!,listenerName:_name.text,phone:_phone.text);if(mounted)setState(()=>_result=result);}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString())));}finally{if(mounted)setState(()=>_sending=false);}}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Concursos y dinámicas')),body:SafeArea(child:_loading?const Center(child:CircularProgressIndicator(color:AppTheme.orange)):_error!=null?_message(Icons.error_outline_rounded,'No pudimos cargar la dinámica',_error!):_result!=null?_resultView():_contest==null?_message(Icons.emoji_events_outlined,'No hay dinámicas activas','Sigue escuchando Somos Radio para conocer la próxima.'):_questionView()));
 Widget _questionView(){final c=_contest!;return ListView(padding:const EdgeInsets.all(20),children:[Container(padding:const EdgeInsets.all(22),decoration:BoxDecoration(color:AppTheme.orange.withValues(alpha:.10),borderRadius:BorderRadius.circular(24),border:Border.all(color:AppTheme.orange.withValues(alpha:.3))),child:Column(children:[const Icon(Icons.emoji_events_rounded,color:AppTheme.orange,size:48),const SizedBox(height:12),Text(c.title,textAlign:TextAlign.center,style:const TextStyle(fontSize:22,fontWeight:FontWeight.w900)),if(c.prize?.isNotEmpty==true)...[const SizedBox(height:8),Text('Premio: ${c.prize}',textAlign:TextAlign.center,style:const TextStyle(color:AppTheme.orange,fontWeight:FontWeight.w800))]])),const SizedBox(height:22),Text(c.question,style:const TextStyle(fontSize:20,fontWeight:FontWeight.w900,height:1.3)),const SizedBox(height:16),...c.options.entries.map((e)=>Padding(padding:const EdgeInsets.only(bottom:10),child:RadioListTile<String>(value:e.key,groupValue:_selected,onChanged:(v)=>setState(()=>_selected=v),title:Text('${e.key}. ${e.value}',style:const TextStyle(fontWeight:FontWeight.w700)),activeColor:AppTheme.orange,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(16)),tileColor:Colors.white.withValues(alpha:.04)))),const SizedBox(height:8),TextField(controller:_name,decoration:const InputDecoration(labelText:'Tu nombre (opcional)')),const SizedBox(height:10),TextField(controller:_phone,keyboardType:TextInputType.phone,decoration:const InputDecoration(labelText:'Teléfono (opcional)')),const SizedBox(height:18),FilledButton(onPressed:_selected==null||_sending?null:_submit,style:FilledButton.styleFrom(backgroundColor:AppTheme.orange,foregroundColor:Colors.black,padding:const EdgeInsets.symmetric(vertical:16)),child:Text(_sending?'ENVIANDO...':'ENVIAR RESPUESTA',style:const TextStyle(fontWeight:FontWeight.w900)))]);}
 Widget _resultView(){final r=_result!;if(r.isWinner)return ListView(padding:const EdgeInsets.all(20),children:[const SizedBox(height:20),const Icon(Icons.emoji_events_rounded,color:AppTheme.orange,size:78),const SizedBox(height:16),const Text('¡FELICIDADES!\nGANASTE',textAlign:TextAlign.center,style:TextStyle(fontSize:28,fontWeight:FontWeight.w900)),if(r.prize?.isNotEmpty==true)...[const SizedBox(height:12),Text(r.prize!,textAlign:TextAlign.center,style:const TextStyle(fontSize:18,color:AppTheme.orange,fontWeight:FontWeight.w800))],const SizedBox(height:24),Container(padding:const EdgeInsets.all(22),decoration:BoxDecoration(color:Colors.white.withValues(alpha:.06),borderRadius:BorderRadius.circular(22),border:Border.all(color:AppTheme.orange.withValues(alpha:.35))),child:Column(children:[const Text('FOLIO DE GANADOR',style:TextStyle(color:Colors.white54,fontSize:11,fontWeight:FontWeight.w800,letterSpacing:1.5)),const SizedBox(height:8),SelectableText(r.claimCode??'',style:const TextStyle(fontSize:24,fontWeight:FontWeight.w900,color:AppTheme.orange)),const SizedBox(height:12),Text(r.redemptionInstructions?.isNotEmpty==true?r.redemptionInstructions!:'Presenta esta pantalla para reclamar tu premio.',textAlign:TextAlign.center,style:const TextStyle(color:Colors.white70,height:1.4))])),const SizedBox(height:16),const Text('Este comprobante seguirá disponible aquí hasta que tu premio sea marcado como entregado.',textAlign:TextAlign.center,style:TextStyle(color:Colors.white54,fontSize:12,height:1.4))]);return _message(r.isCorrect?Icons.check_circle_outline_rounded:Icons.favorite_outline_rounded,r.isCorrect?'¡Respuesta correcta!':'Gracias por participar',r.isCorrect?'Tu respuesta fue correcta, pero los lugares ganadores disponibles ya fueron asignados.':'Sigue escuchando Somos Radio para participar en las próximas dinámicas.');}
 Widget _message(IconData icon,String title,String text)=>Center(child:Padding(padding:const EdgeInsets.all(28),child:Column(mainAxisSize:MainAxisSize.min,children:[Icon(icon,color:AppTheme.orange,size:64),const SizedBox(height:18),Text(title,textAlign:TextAlign.center,style:const TextStyle(fontSize:23,fontWeight:FontWeight.w900)),const SizedBox(height:10),Text(text,textAlign:TextAlign.center,style:const TextStyle(color:Colors.white60,height:1.5))])));
}
